FROM php:8.1.16-fpm


RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    zlib1g-dev \
    cron \
    nano \
    libxml2-dev \
    libzip-dev \
   && docker-php-ext-install \
    zip \
    intl \
    mysqli \
    pdo pdo_mysql 


RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer


WORKDIR /var/www/symfony
